# Generator

1. 下面结果是什么？为什么？

```js
function* demo() {
  console.log('Hello' + yield);
  console.log('Hello' + yield 123);

  console.log('Hello' + (yield));
  console.log('Hello' + (yield 123));

  foo(yield 'a', yield 'b');
  let input = yield;
}
```

<details>
<summary>答案</summary>

```js
function* demo() {
  console.log('Hello' + yield); // SyntaxError
  console.log('Hello' + yield 123); // SyntaxError

  console.log('Hello' + (yield)); // OK
  console.log('Hello' + (yield 123)); // OK

  foo(yield 'a', yield 'b'); // OK
  let input = yield; // OK
}
```

* yield表达式如果用在另一个表达式之中，必须放在圆括号里面
* yield表达式用作函数参数或放在赋值表达式的右边，可以不加括号

</details>
<br><br>

2. 下面结果是什么？为什么？

```js
function* foo() {
  yield 1;
  yield 2;
  yield 3;
  yield 4;
  yield 5;
  return 6;
}

for (let v of foo()) {
  console.log(v);
}
```

<details>
<summary>答案</summary>

```js
function* foo() {
  yield 1;
  yield 2;
  yield 3;
  yield 4;
  yield 5;
  return 6;
}

for (let v of foo()) {
  console.log(v);
}
// 1 2 3 4 5
```

一旦 next 方法的返回对象的 done 属性为 true，for...of 循环就会中止，且不包含该返回对象。例如下面这些操作：

```js
function* numbers () {
  yield 1
  yield 2
  return 3
  yield 4
}

// 扩展运算符
[...numbers()] // [1, 2]

// Array.from 方法
Array.from(numbers()) // [1, 2]

// 解构赋值
let [x, y] = numbers();
x // 1
y // 2

// for...of 循环
for (let n of numbers()) {
  console.log(n)
}
// 1
// 2
```
</details>
<br><br>

3. 下面的结果是什么？为什么？

```js
var gen = function* gen(){
  try {
    yield console.log('a');
  } catch (e) {
    // ...
  }
  yield console.log('b');
  yield console.log('c');
}

var g = gen();
g.next()
g.throw()
g.next()
```

<details>
<summary>答案</summary>

```js
var gen = function* gen(){
  try {
    yield console.log('a');
  } catch (e) {
    // ...
  }
  yield console.log('b');
  yield console.log('c');
}

var g = gen();
g.next() // a
g.throw() // b
g.next() // c
```

* throw 方法被捕获以后，会附带执行下一条 yield 表达式。也就是说，会附带执行一次next方法
* 只要 Generator 函数内部部署了 try...catch 代码块，那么遍历器的 throw 方法抛出的错误，不影响下一次遍历
</details>
<br><br>

4. 下面的结果是什么？为什么？

```js
function* numbers () {
  yield 1;
  try {
    yield 2;
    yield 3;
  } finally {
    yield 4;
    yield 5;
  }
  yield 6;
}
var g = numbers();
g.next()
g.next()
g.return(7)
g.next()
g.next()
```

<details>
<summary>答案</summary>

```js
function* numbers () {
  yield 1;
  try {
    yield 2;
    yield 3;
  } finally {
    yield 4;
    yield 5;
  }
  yield 6;
}
var g = numbers();
g.next() // { value: 1, done: false }
g.next() // { value: 2, done: false }
g.return(7) // { value: 4, done: false }
g.next() // { value: 5, done: false }
g.next() // { value: 7, done: true }
```

* 如果 Generator 函数内部有 try...finally 代码块，且正在执行 try 代码块，那么 return() 方法会导致立刻进入 finally 代码块，执行完以后，整个函数才会结束
* 调用 return() 方法后，就开始执行 finally 代码块，不执行 try 里面剩下的代码了，然后等到 finally 代码块执行完，再返回 return() 方法指定的返回值
</details>
<br><br>

5. 使用 Generator 函数实现数组的平铺（flat）？


<details>
<summary>答案</summary>

```js
function* iterTree(tree) {
  if (Array.isArray(tree)) {
    for(let i=0; i < tree.length; i++) {
      yield* iterTree(tree[i]);
    }
  } else {
    yield tree;
  }
}

const tree = [ 'a', ['b', 'c'], ['d', 'e'] ];

for(let x of iterTree(tree)) {
  console.log(x);
}
// a
// b
// c
// d
// e

[...iterTree(tree)] // ["a", "b", "c", "d", "e"]
```
</details>
<br><br>
